8 post a new comment to an existing review
rovercode1/frontend-nc-games pull request #5
Opened 2023-03-15 12:22 UTC by rovercode1

2023-03-15 12:52 UTC, Slyose reviewed
Great stuff so far! Two things to consider 
- Your comments p tag on the list reviews page isn't being used for anything at the moment
- The user should be given feedback on unsuccessful post (one approach to this is having a state that keeps track of if an error has occured, the conditionally render a <p tag saying that the comment wasn't posted)

2023-03-15 12:52 UTC, Slyose commented on src/Components/ArticleList.jsx
>            <p>Comments</p>
This doesn't actually do or show anything yet. Did you mean to show the comment count here?

2023-03-16 10:23 UTC, HannahBurks requested changes
A nice start Dean 😄 
One other thing I would note, is that it isn't very responsive - it should be a mobile first design- then use something like media queries to make it adaptable. For instance, the photo on individual reviews is too big in mobile view, it stretches.

A few changes to be made (as per my comments on the code) Once done, please send another PR 😄

2023-03-16 10:23 UTC, HannahBurks commented on src/Components/SingleReview.jsx
> +    const postedAt = review.created_at
We never use this variable - I would either delete it or use it. The same goes for any states we don't use

2023-03-16 10:23 UTC, HannahBurks commented on src/Components/PostComment.jsx
> +    e.preventDefault();
When posting I can click submit multiple times and it posts duplicates - we need to add some logic to disable it whilst it is posting 

2023-03-16 10:23 UTC, HannahBurks commented on src/Components/ArticleList.jsx
> +    console.log(review)
remove any console logs such as this :)

2023-03-16 14:08 UTC, HannahBurks approved these changes
Nice one Dean 👏🏼 Merge away!

2023-03-16 14:43 UTC, merged